import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler

min_max = MinMaxScaler()
z_score = StandardScaler()

df1 = pd.read_csv('ITA105_Lab_3_Sports.csv').dropna()
plt.boxplot(df1['chieu_cao_cm'])
plt.title('Bai 1: Boxplot Chieu Cao')
plt.show()
df1['chieu_cao_MinMax'] = min_max.fit_transform(df1[['chieu_cao_cm']])
df1['chieu_cao_ZScore'] = z_score.fit_transform(df1[['chieu_cao_cm']])
plt.hist(df1['chieu_cao_cm'], alpha=0.5, label='Goc')
plt.hist(df1['chieu_cao_MinMax'], alpha=0.5, label='Min-Max')
plt.hist(df1['chieu_cao_ZScore'], alpha=0.5, label='Z-Score')
plt.title('Bai 1: So sanh Chieu Cao')
plt.legend()
plt.show()

df2 = pd.read_csv('ITA105_Lab_3_Health.csv').dropna()
plt.boxplot(df2['huyet_ap_mmHg'])
plt.title('Bai 2: Boxplot Huyet Ap')
plt.show()
df2['huyet_ap_MinMax'] = min_max.fit_transform(df2[['huyet_ap_mmHg']])
df2['huyet_ap_ZScore'] = z_score.fit_transform(df2[['huyet_ap_mmHg']])
plt.hist(df2['huyet_ap_mmHg'], alpha=0.5, label='Goc')
plt.hist(df2['huyet_ap_MinMax'], alpha=0.5, label='Min-Max')
plt.hist(df2['huyet_ap_ZScore'], alpha=0.5, label='Z-Score')
plt.title('Bai 2: So sanh Huyet Ap')
plt.legend()
plt.show()

df3 = pd.read_csv('ITA105_Lab_3_Finance.csv').dropna()
plt.boxplot(df3['doanh_thu_musd'])
plt.title('Bai 3: Boxplot Doanh Thu')
plt.show()
df3['doanh_thu_MinMax'] = min_max.fit_transform(df3[['doanh_thu_musd']])
df3['doanh_thu_ZScore'] = z_score.fit_transform(df3[['doanh_thu_musd']])
df3['loi_nhuan_MinMax'] = min_max.fit_transform(df3[['loi_nhuan_musd']])
df3['loi_nhuan_ZScore'] = z_score.fit_transform(df3[['loi_nhuan_musd']])
plt.scatter(df3['doanh_thu_musd'], df3['loi_nhuan_musd'], alpha=0.6, label='Goc')
plt.scatter(df3['doanh_thu_ZScore'], df3['loi_nhuan_ZScore'], alpha=0.6, label='Z-Score')
plt.title('Bai 3: Scatterplot Doanh thu vs Loi nhuan')
plt.legend()
plt.show()

df4 = pd.read_csv('ITA105_Lab_3_Gaming.csv').dropna()
plt.boxplot(df4['gio_choi'])
plt.title('Bai 4: Boxplot Gio Choi')
plt.show()
df4['gio_choi_MinMax'] = min_max.fit_transform(df4[['gio_choi']])
df4['gio_choi_ZScore'] = z_score.fit_transform(df4[['gio_choi']])
plt.hist(df4['gio_choi'], alpha=0.5, label='Goc')
plt.hist(df4['gio_choi_MinMax'], alpha=0.5, label='Min-Max')
plt.hist(df4['gio_choi_ZScore'], alpha=0.5, label='Z-Score')
plt.title('Bai 4: So sanh Gio Choi')
plt.legend()
plt.show()